Add required <string> header
Without this, clang emits among others:

spice-streaming-agent.cpp:355:31: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    streamfd = open(streamport.c_str(), O_RDWR);
                              ^

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
Acked-by: Frediano Ziglio <fziglio@redhat.com>