test-stream-port: Remove unused variable 'buf'
This with gcc 8 causes:

test-stream-port.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
test-stream-port.cpp:78:18: error: unused variable ‘buf’ [-Werror=unused-variable]
             char buf[10];
                  ^~~

Signed-off-by: Frediano Ziglio <fziglio@redhat.com>
Acked-by: Uri Lublin <uril@redhat.com>