Fix clang build error on missing <errno.h>
Using errno requires <errno.h>. Some platforms/compilers
are stricter than others in this respect.

frame-log.cpp:27:96: error: use of undeclared identifier 'errno'
           throw Error(std::string("Failed to open log file '") + log_name + "': " + strerror(errno));